### ISSUE TITLE
Read ""Incentives Promote Peer Pressure in an Energy Saving Campaign"

### ISSUE THREAD

**Issue by dazzaji** [codeforboston/cambridge_energy_app#1]
Cite: Ankur Mani, Claire Michelle-Loock, Iyad Rahwan, Thorsten Staake, Elgar Fliesch, and Alex Pentland, "Incentives Promote Peer Pressure in an Energy Saving Campaign," in submission (presented at Netsci, 2013 and Behavior Energy and Climate Change Conference, 2013).

I can make an introduction to the main author, Mani Ankur.  He may have good ideas on ways to apply the approach as best as possible in the Cambridge environment and with the data that is available.

**Comment by mzagaja** [comment]
http://hackwinter2015.devpost.com/forum_topics/5392-project-pitch-apartment-building-energy-savings

**Comment by bdougsand** [comment]
http://www.nature.com/articles/srep01735

**Comment by challyed** [comment]
This may sound repetitive but I do like the idea of having some type of peer pressure implemented in this application.

**Comment by dazzaji** [comment]
Hi Matthew  - noticed that you "self-assigned" this issue to yourself.  Have you had a chance to read the paper yet and think about our options for applying this approach?

**Comment by mzagaja** [comment]
Not yet it's on the docket for this weekend. 

-Matt

**Comment by mzagaja** [comment]
Actually looking back at my e-mail it appears we have not yet procured a copy of this. I tried using the Harvard Library to get a copy and they did not seem to have one. Any chance MIT might have a copy?

**Comment by dazzaji** [comment]
I got the original paper (published in Nature actually) and also a couple choice slide decks.  Apparently don't have rights to this repo.

**Comment by mzagaja** [comment]
Weird, try again. I think I didn't set the settings correctly in the collaborators screen. Sorry even though I use GitHub for code stuff I'm a bit new to that side of things.

**Comment by dazzaji** [comment]
Will do, thanks!

**Comment by mzagaja** [comment]
Ok I'm going to mark this closed. The ideas that were in there mostly tracked our conversation:
1. Putting people in teams
2. Making sure everyone can see their teammates progress
3. Rewarding people for the improvements that their teammates made is more effective than rewarding them for their own activity. 

I think the team dynamic is covered in our discussion/PR around the model (and if not then we can make a new issue for that). But I do think we need a new issue to further brainstorm potential rewards which I will open.
