### ISSUE TITLE
Send reset instructions gives error

### ISSUE THREAD

**Issue by mahtai** [codeforboston/cambridge_energy_app#105]
![image](https://cloud.githubusercontent.com/assets/15893384/14837651/48adc338-0be8-11e6-9c41-b3bc5bd9b04b.png)
Note: Bug 5 on Jeremiah's list

**Comment by mahtai** [comment]
"We're sorry but something went wrong" on live site, bug 14 on Jeremiah's list

**Comment by mzagaja** [comment]
Fixed by adding the send grid credentials to the Heroku account: http://stackoverflow.com/questions/32492883/sendgrids-550-unauthenticated-senders-not-allowed-in-rail-app
