### ISSUE TITLE
Unit creation error

### ISSUE THREAD

**Issue by mahtai** [codeforboston/cambridge_energy_app#107]
Attempting to create a unit from a user profile page doesn't work because it expects a user_building key, which probably doesn't exist at this point. We should just remove that field from the form and have it set by some internal mechanism.
Note: Bug 7 on Jeremiah's list

**Comment by itiswicked** [comment]
I will make this my project for tomorrow!

**Comment by itiswicked** [comment]
So I'm thinking the best solution for this is allowing a user to type in an address in place of a user_building, they will get a list of addresses available for auto-complete. These will be addresses that already exist in the user_buildings table.

When the form is submitted it will be submitted with a user_building_id if the user has 'selected' a pre-existing address, or if not submitted with an id, the action will know that it needs to create a new record on that table.

There are a few minimalist JS libraries that I will explore to accomplish this.

**Comment by mahtai** [comment]
A similar auto-fill option maybe should be available for existing units as well.
