### ISSUE TITLE
"Index" pages should be removed

### ISSUE THREAD

**Issue by mahtai** [codeforboston/cambridge_energy_app#109]
I don't think there are any index pages we actually want. Plus, the current index pages include "show", "edit" and "destroy" options for any instances they index regardless of who the current user is, which we definitely do not want.

**Comment by mzagaja** [comment]
Not sure we should remove these but certainly secure them from regular users. Maybe we should have an admin user that can access these.

**Comment by mzagaja** [comment]
Please inventory the pages that should and shouldn't be public and consider implementing a gem like https://github.com/elabs/pundit to create role based authorization. We also might want to create a page for an administrator type user that lists the available index pages in the UI for them.

**Comment by mzagaja** [comment]
Pundit has been implemented so this issue is stale.
