### ISSUE TITLE
Inventory of Discount Programs

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#11]
As part of content development one of the things we will likely want to have is an inventory of the various financial incentives and subsidies available to help people purchase energy saving upgrades. UI/UX will then be responsible for figuring out how to best communicate these to the users in a way that spurs them to take advantage.

From this inventory we may then want to create a bunch of "features" that help people easily take advantage of them. This may include bringing them to Amazon.com to purchase an item and telling them where to send a receipt for a rebate, or even contacting the appropriate partner to see if we can directly interface with their system to get requests put in.

**Comment by mzagaja** [comment]
@challyed would you be able to do this research and report back by Saturday with:

What incentives are available
The process for applying for each incentive that includes any intake capabilities via fax, e-mail, web form or USPS. Make sure to include relevant URLs.
Once this initial phase is done we can hand it off to a developer to build the appropriate wrapper/adapter.

**Comment by challyed** [comment]
This website has a pretty good list of Incentives, displays it by name, type of incentive, type of category.  Also If you "dig" into the name it gives more information 
http://programs.dsireusa.org/system/program?zipcode=02145 
This resources also has a database archive. 
http://www.dsireusa.org/resources/database-archives/
[Uploading dsire-2015-09.zip…]()

**Comment by mzagaja** [comment]
I think that http://www.masssave.com/en/residential/mass-energy-rebate is probably a little easier to process at this point. Some of these already have online forms and so I think we can just lift the content from Mass Save and then link to the relevant form instead of writing a wrapper, but the MassSave form is kind of long and it'd be cool if we could find a way to improve on these forms: https://efi.secure.force.com/client/FormMAAPPV1.
