### ISSUE TITLE
Cannot access profile on live site

### ISSUE THREAD

**Issue by mahtai** [codeforboston/cambridge_energy_app#110]
Signing in with Google link, adding account yields undescriptive "something went wrong" error instead of profile page.
Note: Bug 12 on Jeremiah's list

**Comment by danielmruk** [comment]
Submitted a possible fix for this. It looks like the scope was not set in Google Auth. Is it possible to get the heroku log screen shots, similar to the password reset issue? The fix is Google Auth Scope.

**Comment by mzagaja** [comment]
Fixed by #171
