### ISSUE TITLE
Cannot create bill while logged in on live site

### ISSUE THREAD

**Issue by mahtai** [codeforboston/cambridge_energy_app#111]
"We're sorry, but something went wrong" when logged in on live site. Creating bill works fine as guest.
Note: Bug 15 on Jeremiah's list

**Comment by mahtai** [comment]
Hmm. I was able to create a bill when logged in on the live site, but it appears to have created a duplicate as well.

**Comment by mahtai** [comment]
Duplication issue not replicated yet. Can still put in bills when logged in.

**Comment by mahtai** [comment]
Getting "Something went wrong" now when logged in.

**Comment by mahtai** [comment]
More duplication issues, a few "something went wrongs". No observable pattern so far.

**Comment by kvotolato3** [comment]
I have entered 3 bills as a logged in user in production and have not gotten the error.

**Comment by mzagaja** [comment]
Closing due to lack of reproducible test case.
