### ISSUE TITLE
Labeling Issue Topics

### ISSUE THREAD

**Issue by JerJohn15** [codeforboston/cambridge_energy_app#124]
Hey everyone, 

I was wondering if, at some point @mzagaja,  you, or whoever has rights to create labels, could consider labeling each topic so that it is easier for us to tell a bug, from a question or idea. I know GitHub has default labels for bugs but perhaps the following labels could be created:
- **low hanging fruits** - minor bugs that are not of a huge concern
- **high hanging fruits** - bugs that are more severe
- **Ideas** - potential ideas (could also be called "suggestions" or "brainstorming"
- **Question** - the name says it all

**Comment by mzagaja** [comment]
I've started using labels so I'm going to close this. I don't think I want to differentiate between the low and high hanging fruits because there are other factors (like skill level, etc.) to consider when taking bugs. I tend to label items that are friendly for newcomers to take as "help wanted".
