### ISSUE TITLE
Access Denied is Flashed after Successful Login

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#134]
After logging in with my user account on my local machine I was sent to my profile page and received an access denied message:

<img width="410" alt="screenshot 2016-05-01 18 47 29" src="https://cloud.githubusercontent.com/assets/565647/14944800/4aa62354-0fcd-11e6-9279-35ff921ddd69.png">

**Comment by JerJohn15** [comment]
@mzagaja 

When I login, on my local version, it says, "Signed in successfully", however, when I try to create a new unit and click the "create unit" button, I am presented with the same "access denied" message, in which you are getting.

I've added this to my bug report (see Bug 17,  #102).

**Comment by mahtai** [comment]
So that means that the authorization bit is too zealous. I'll try to fix this.

**Comment by mahtai** [comment]
So the issue with the units is that you can create a unit without being in it. I'm not sure if we want this kind of behavior or not.

**Comment by mahtai** [comment]
Pull request #137 fixes the unit issue. I'm still not sure what the issue @mzagaja got was; I can't reproduce it.

**Comment by itiswicked** [comment]
Just FYI, in `config/locals`, there are devise generated files that define the global notices, so you can change messages there.

**Comment by danielmruk** [comment]
I went through and tested this multiple times. I wasn't able to get the access denied message either.

**Comment by mzagaja** [comment]
I think this might have been a local issue on my machine then, probably needed a rake db:reset. Going to close as not reproducible for now.
