### ISSUE TITLE
Bill duplication on graph

### ISSUE THREAD

**Issue by mahtai** [codeforboston/cambridge_energy_app#140]
On both local and live, when I submit a bill it sometimes shows up multiple times on the graph. It doesn't appear as multiple bills in the bills#index, just on the graph.

**Comment by mzagaja** [comment]
Same. I'll take a look.

**Comment by mzagaja** [comment]
The issue is the graph determines the current user amount by looking at the amount instead of looking at the user id. Lets avoid this edge case for now and I'll try fixing it later.

**Comment by mahtai** [comment]
So by adding a user attribute to the data being fed into the draw function, I am able to get the graph to select by user rather than by amount. This has the effect of selecting all of the user's bills submitted. Edge cases are now that if a user has submitted multiple bills then all of them will be selected. Filtering and validation should deal with that. Perhaps I can get it to look at dates as well to just grab the latest bill.
See the d3testing branch for code.

**Comment by itiswicked** [comment]
Could you send the bill id in question to the client with the JSON payload
and match to a specific bill with that ID? So the JSON would look like {
bill_id: 7, bills: [ . . . ] }, and all bills would be sent with their id.

**Comment by mahtai** [comment]
That works great. d3 branch updated.
