### ISSUE TITLE
Providing better dummy data

### ISSUE THREAD

**Issue by itiswicked** [codeforboston/cambridge_energy_app#148]
Change seed info:
- Emails should have a non-existant domain so we're not sending an email to an actual email account
- Bill amount should be a float with any number of cents.

**Comment by mahtai** [comment]
Is there some way to make sure that each user has the current and the previous months for bills? That's what the scoring system is currently looking for. The scoring system is currently a computation done on bills so I don't think it can just be set in a seed.

**Comment by whilei** [comment]
You're not sending actual emails in development, right?

**Comment by mzagaja** [comment]
Closing as WONTFIX since we no longer want to use dummy data.
