### ISSUE TITLE
Add Green Button Integration for Energy Data Downloads

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#16]
http://www.greenbuttondata.org/

We may need to contact Eversource to get authorized. We need to review the documentation to ascertain how to integrate this with the rails app.

**Comment by mzagaja** [comment]
I sent an e-mail to the generic info address to get access to this. The e-mail bounced so I opened an issue on the website's GitHub repo https://github.com/green-button/green-button.github.io/issues/118. Hopefully the development team will get us an appropriate contact point. If I don't hear by Friday I'll try and see if there is another contact point.

**Comment by mzagaja** [comment]
Information on obtaining authorization is allegedly in the below document that I'm uploading here for future reference. Marty sends the following note along with it:

The end points of the Data Custodian you are communicating with are part of the needed parameters in for the ApplicationInformation  data structure which represents the shared relationship between a DataCustodian and a ThirdParty.

Some help on using the APIs is on http://www.greenbuttondata.org/developers/sandbox/.

In order to communicate with a DataCustodian  you will need:

DataCustodian endpoints

Your endpoints

Exchange of secure certificates with DataCustodian

Perform the scope negotiation sequence prior to redirecting RetailCustomer to DataCustodian

Extension of OAuth2.0 to provide the required parameters returned during the authorization

[GreenButtonAuthorization.docx](https://github.com/codeforboston/cambridge_energy_app/files/61216/GreenButtonAuthorization.docx)

**Comment by dazzaji** [comment]
Here is an update for making this work (which is worth doing):

Marty Burns at NIST is probably best bet for GB technical questions, as he helped developed the GB standard & is very knowledgeable/responsive: Burns, Martin martin.burns@nist.gov

The team at the Green Button Alliance, which is the recently launched industry-led group for GB standards & certification, is also a good resource. GB leaders are working transition GB leadership and expertise from Feds/NIST/DOE to private sector: http://www.greenbuttonalliance.org/contact/

**Comment by mzagaja** [comment]
Thanks Dazza Marty is the one I've been in contact via e-mail over the past day.

**Comment by mzagaja** [comment]
Just memorializing the email responses I got:

> Hello, Matthew: 
> 
> I thought I might add-on to the reply Marty gave.  It's always great to hear about new developments for >the Green Button ecosystem and we certainly want you to succeed.  Ruby and ROR are not too familiar >to our team; however, GB files/streams are simply Atom RSS XML feeds with specific information >represented by the derived NAESB ESPI REQ.21 XSD inside, so if you are familiar with XML parsing >and you are familiar with OAUTH2, then you're on your way. 
> 
> There is indeed a gem project at https://github.com/cew821/greenbutton to help get you started; >however, it was written in February of 2014 and has not been updated since May of 2014.  Therefore, it >does not support any of the updates to the espiDerived.xsd file that have been released this year.  Also, >a note of warning: be sure your design does not marshal the Green Button data stream in memory.  >While that works well for testing, when there is a request for, say, 13 months of data at 15-minute >intervals, it will often exceed the memory capacity of such an in-memory design. 
> 
> As I mentioned, we do not have Ruby or ROR expertise on staff; however, if you have further technical >questions about GB implementation in general, we do have the ability to support you through >membership in the Green Button Alliance or through hourly paid support.  Unfortunately, our technical >resources are very limited while we build-out our CMD Certification suite of testing tools; so as a >nonprofit organization, we need to keep to supporting members first and foremost.  Participating >Membership includes two hours of tech time, if you are interested, with other hours at $250 each. 
> 
> Lastly, since "Eversource" is an umbrella of several, previously separate operating companies, there >may be different offerings for the different geographies.  If you know of the previous name of the >Eversource in your area, that may help us find you the API endpoints.  However, I'm not aware of a full >CMD implementation by Eversource as a whole; though their DMD implementation is companywide >now. 
> 
> Thanks for contacting us, Matthew, 
> - Jeremy
> 
> Matt,
> 
> The end points of the Data Custodian you are communicating with are part of the needed parameters in for the >ApplicationInformation  data structure which represents the shared relationship between a DataCustodian and a> ThirdParty.
> 
> Some help on using the APIs is on http://www.greenbuttondata.org/developers/sandbox/.
> 
> In order to communicate with a DataCustodian  you will need:
> 
> DataCustodian endpoints
> 
> Your endpoints
> 
> Exchange of secure certificates with DataCustodian
> 
> Perform the scope negotiation sequence prior to redirecting RetailCustomer to DataCustodian
> 
> Extension of OAuth2.0 to provide the required parameters returned during the authorization
> 
> Documentation on these aspects can be found at http://osgug.ucaiug.org/sgsystems/OpenADE/Shared%20Documents/>Testing%20and%20Certification/GreenButtonTestPlan/referenceMaterial/GreenButtonAuthorization.docx.>
> 
> HTH,
> 
> Marty

**Comment by dazzaji** [comment]
Hey, just clarifying - at this point, is the only missing information needed to integrate Green Button into our Cambridge Energy App (EnerSave) just the URL for the endpoint?  And did you tell the Green Button team that the previous name of the Eversource in the Cambridge area was Nstar?

**Comment by mzagaja** [comment]
Yep

-Matt

**Comment by mzagaja** [comment]
> Hi Jeremy,
> 
> Thanks so much for getting back to me, and apologies for the tardy reply as things were on hold for me with the holiday. This is definitely helpful. In Cambridge the provider's previous name was NStar. Is there an API endpoint for them, or someone there we should chat with to get that?
> 
> Best,
> 
> Matt

**Comment by mzagaja** [comment]
I e-mailed Tom Reid from Mass Clean Energy Center and he is going to reach out to Eversource on our behalf:

> Hi Tom,
> 
> It was good to meet you earlier. Thanks so much for offering to help with getting us access to the Green Button API. We are looking for a way to get access to the API endpoints from Eversource. Specifically we are looking for documentation on what the appropriate URLs are to get the data along with whatever access tokens we might need. Further elaboration on this issue can be found on our GitHub page at https://github.com/codeforboston/cambridge_energy_app/issues/16. Also feel free to check out and learn more about our app from our main GitHub page at: https://github.com/codeforboston/cambridge_energy_app. Thanks again for your help.
> 
> -Matt

**Comment by mzagaja** [comment]
On Friday I called and e-mailed a friend at EverSource investor relations. I am hopeful this will yield a useful connection.

**Comment by mzagaja** [comment]
EverSource said they have not currently implemented "Connect My Data" on their system but are willing to work with us when they do it next year. I will consider this closed when we merge #243
