### ISSUE TITLE
NoMethodError in Users#show

### ISSUE THREAD

**Issue by kvotolato3** [codeforboston/cambridge_energy_app#172]
On my local dev environment, this happens when I create a new account, add a bill, and click on my profile. 

![image](https://cloud.githubusercontent.com/assets/6846463/15344152/2ba51d6e-1c72-11e6-8d77-27eec3837dbb.png)

**Comment by mzagaja** [comment]
I think there was a breaking change in one of the pull requests I merged. Try a rake db:reset and see if it still happens? I had to delete my account and create a new one to fix this on mine as I had the same error last night.

**Comment by kvotolato3** [comment]
Somehow this issue seems to be fixed on the Master branch. I can no longer reproduce it on my local dev.
