### ISSUE TITLE
Tip Sharing

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#192]
The tip sharing button doesn't work yet. We want it to share the fact the person executed the tip to Facebook. It'd be great if each tip had appropriate social content associated with it as well.

**Comment by mahtai** [comment]
Travis is giving me a weird error because I'm trying to use a gem and Travis is apparently unhappy with installing stuff while in deployment mode. Is this because we're trying to launch, or is Travis just misconfigured?
Pull request #210

**Comment by mzagaja** [comment]
You need to bundle install the required gem and then check in the updated Gemfile.lock. 

-Matt

**Comment by mahtai** [comment]
Great! It passes now. Wish Travis gave a more comprehensible report.
