### ISSUE TITLE
Team Dashboard

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#23]

**Comment by mzagaja** [comment]
Cap teams at 8
Compare teams/people based on percentage reductions.

Model
Team Members
Team Name
Image 

Start a Team
Join a Team - pick from list of teams

**Comment by mzagaja** [comment]
Update: People can only join teams by letting existing team members invite them.

**Comment by mahtai** [comment]
Is there a nice way to give team images other than something like gravatar, which requires an email address? Or do we want to be making a dummy account for each team?

**Comment by mzagaja** [comment]
I think we can have a stock image (or library of stock images) that we assign to teams by default and then let them upload their own.

**Comment by sonya** [comment]
There are some websites that provide APIs to request random images

http://avatars.adorable.io/
https://robohash.org/

Also, Faker has an avatar function that uses robohash. https://github.com/stympy/faker#fakeravatar
@Jngai has an open pull request that includes Faker.
