### ISSUE TITLE
undefined method `user_omniauth_authorize_path' on users/sign_in

### ISSUE THREAD

**Issue by kvotolato3** [codeforboston/cambridge_energy_app#236]
I'm getting this error when I try to log in on my local dev environment (master branch). I just completed a git merge from origin, and ran bundle, so everything should be totally up to date at this point. Am I missing something? Anyone else encountering this?

NoMethodError in Devise::Sessions#new
undefined method `user_omniauth_authorize_path' for #<#Class:0x007fefae029888:0x007fefae013c18>

Extracted source (around line #22):
`<%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2)%>`

**Screenshot:**
![image](https://cloud.githubusercontent.com/assets/6846463/17113738/f4f04a58-5279-11e6-923e-86ec3b428d2e.png)

**Comment by mahtai** [comment]
I'm getting the same error for both logging in and signing up.
