### ISSUE TITLE
Key User Interfaces and Flows

### ISSUE THREAD

**Issue by dazzaji** [codeforboston/cambridge_energy_app#25]
A basic outline listing to start with:

Enrollment
Pick a buddy or team
   [Project note: Special Credit for Social Graph Fueled Recommomenders]
Enter last month’s energy bill
   [Project note: Take “4-corner” positioned photo and auto-upload to destination. 
See leaderboard
Review your own data/behavior/performance

**Comment by mzagaja** [comment]
This was developed in #2 and also with the stuff that @33eyes did in Moqups for the presentation. UI/UX stuff can now probably best be viewed in the presentation itself which is at https://www.icloud.com/keynote/0005QKW2T1kDblj36EfDYEfgA#EnerSave_Demo_Night_Presentation.
