### ISSUE TITLE
How about integration with Nest?

### ISSUE THREAD

**Issue by 33eyes** [codeforboston/cambridge_energy_app#26]
I am suggesting this for later, not for this Tuesday, of course.

Nest thermostat/etc has cloud API: https://developer.nest.com/
In addition to Nest app and cloud, they are adding Nest Weave in 2016, which would allow connection to other home devices. 
Nest also has an app store for Nest-certified apps, which could introduce our app to the Nest user audience.
Nest's security guidelines for user energy consumption data seem very relevant to our app, and it would be cool if we could follow them. 
National Grid has partnered with Nest in Massachusetts, and offers a rebate for Nest: https://nest.com/energy-partners/national-grid/

Nest integration could be another alternative to gathering energy use data, in addition to scanning bills and green button data. 
And their user base would probably be more likely to try out our app as early adopters (and then hopefully spread the word beyond Nest users), since they were already interested enough in energy conservation to invest in Nest stuff.

**Comment by mzagaja** [comment]
Also interesting to note they actually have a similar concept to our app at: https://www.myenergy.com but it looks like an acquisition they made to use for content marketing type purposes.

**Comment by mzagaja** [comment]
Closing this because nobody has picked it up and I think Nest might be too limited of an audience to work on in the foreseeable future.
