### ISSUE TITLE
Login page, 'sign in with google' seems out of place

### ISSUE THREAD

**Issue by suzannehillman** [codeforboston/cambridge_energy_app#261]
I think this may be because I'm accustomed to seeing the google logo and a signin box for that, rather than just a link.

I'm a little surprised that https://developers.google.com/identity/sign-in/web/ or https://developers.google.com/identity/sign-in/web/build-button isn't already enabled for this purpose. My guess is that you've just not gotten there yet? 

Regardless, I suspect it'd be much easier for people to notice if it looks like they expect a login to look like. Maybe have tabs, where one lets you log in with an email, and the other lets you log in with google?

Something like the following, maybe?

![image](https://cloud.githubusercontent.com/assets/18105933/17640331/56f98a48-60cb-11e6-9482-fe6445fce4bd.png)

**Comment by JosephinaTavera** [comment]
Will take a look

**Comment by JosephinaTavera** [comment]
Notice that 'Sign in with Google' appears twice on screen.  
<img width="1008" alt="signingoogle" src="https://cloud.githubusercontent.com/assets/15881366/18976321/0fca9584-867f-11e6-8853-969746ce6326.png">

link hardcoded in     views/devise/sessions/new.html.erb.    

It is already included in the    devise/shared/links

**Comment by mzagaja** [comment]
Fixed in #317
