### ISSUE TITLE
No "Sign in with Google" on "How does my energy bill compare with my neighbors in Cambridge?" page

### ISSUE THREAD

**Issue by jtrshelley** [codeforboston/cambridge_energy_app#265]
Missing the alternate Google sign in option:

![screen shot 2016-08-16 at 7 41 12 pm](https://cloud.githubusercontent.com/assets/431637/17719554/6fa5eb10-63e9-11e6-99a6-2a25b1be039f.png)

**Comment by mzagaja** [comment]
Resolved in the front end rewrite.
