### ISSUE TITLE
Users can see a "destroy" link for teams they do not own/belong to

### ISSUE THREAD

**Issue by cranti** [codeforboston/cambridge_energy_app#274]
Clicking on it brings up an "are you sure" pop up, but doesn't actually delete the team -- brings you to a page with "The page you were looking for doesn't exist."

**Comment by cranti** [comment]
Related: the "show" and "edit" links are also available for teams that I do not own -- they bring me to my user profile page with an "access denied" message

**Comment by mzagaja** [comment]
This has been resolved.
