### ISSUE TITLE
On any given team page, "Back" and "Me" links don't work

### ISSUE THREAD

**Issue by jtrshelley** [codeforboston/cambridge_energy_app#278]
e.g., from my team page, clicking "Back" and "My Name" links, nothing happens. Just reloads the same team page

**Comment by FrankCardillo** [comment]
I'm going to take a look at this now. Will comment the branch and pull request here when they've been opened.

**Comment by FrankCardillo** [comment]
Branch: https://github.com/codeforboston/cambridge_energy_app/tree/back_and_me_links_issue_278

Pull Request:
https://github.com/codeforboston/cambridge_energy_app/pull/285
