### ISSUE TITLE
Implement new frontend design

### ISSUE THREAD

**Issue by jtrshelley** [codeforboston/cambridge_energy_app#294]
![web wireframe 8 2f16 2f16](https://cloud.githubusercontent.com/assets/431637/18112419/6940af5a-6ef5-11e6-8974-d6916bb291c7.png)

**Comment by tshelley** [comment]
Temporary Key Features images/text:
![previewofkeyfeatures](https://cloud.githubusercontent.com/assets/431637/19501941/83f23d3e-9577-11e6-93f6-ba4bee36e144.png)

Text: Reduce your energy costs!
Get access to energy saving tips and become more aware of your current spending

Compete with friends!
Invite your friends to join your team, and work together to earn great prizes 

Get rewarded with prizes!
Reducing your energy use really pays off with great prizes like CFL light bulbs

Temporary images:
![cash-1297613_640](https://cloud.githubusercontent.com/assets/431637/19501958/91ba7580-9577-11e6-9f3b-756d4538e602.png)

![fluorescent-23990_640](https://cloud.githubusercontent.com/assets/431637/19501970/9f58e014-9577-11e6-9bb3-8ae6341ee073.png)

![icon-1623888_640](https://cloud.githubusercontent.com/assets/431637/19501961/9564a08e-9577-11e6-88f3-b8515bd62a3d.jpg)
