### ISSUE TITLE
OmniAuth Gem with MIT Integration

### ISSUE THREAD

**Issue by dazzaji** [codeforboston/cambridge_energy_app#3]
Find the pull request for the First to Disclose project and see if it is a good fit here!

**Comment by sonya** [comment]
We can use omniauth with other providers. To use the MIT provider we will need someone with MIT credentials to generate the client id and secret for us.

Registration is at https://oidc.mit.edu/manage/dev/dynreg

More info at http://kb.mit.edu/confluence/display/istcontrib/Logging+in+Users+to+your+application+using+OpenID+Connect

**Comment by mzagaja** [comment]
Can @dazzaji do this for us? If not and nobody else in the group is able I can ask around because a bunch of the Berkman fellows are also affiliated with MIT and so I'm sure one can probably help.

**Comment by dazzaji** [comment]
Happy to do it. 

I seem to recall adding MIT as an Identity Provider (IdP) wasn't as well documented or easy to make work as one might hope... but we did achieve a working implementation and it would be great to being this online as a "one click" solution for MIT students. After all, campus relationships are a great overlay for the peer-based incentives approach and that seems to enable big changes in energy saving behavior. 

I'll put some time into this and help connect the dots to onboard MIT as an IdP, use my Kerberos credentials to register the OAuth 2 client/app, test as an MIT user, etc.  If anybody is going to be hacking on the project late afternoon or early evening today, give a holler and let's meet up at media lab, CIC or online to make a dent in this :-)

**Comment by mzagaja** [comment]
@dazzaji If you want me to go ahead with this I just need the appropriate MIT client ID and secret.

**Comment by mzagaja** [comment]
I put the credentials in the Slack channel if someone wants to try and get this working tomorrow.

**Comment by dazzaji** [comment]
cool -i can give it a try with hacker named Akshith who is joining tomorrow night - we are already planning to work on implementing oauth 2 on a legal thing

**Comment by dazzaji** [comment]
Here is more info on revoking OAuth 2 permissions from the app.  It's thought to be a good practice from a user-centered perspective but not widely done and not done the same way across apps/services!  
- Github: https://developer.github.com/v3/oauth_authorizations/#revoke-an-authorization-for-an-application
- Google: https://developers.google.com/identity/protocols/OAuth2WebServer (end of page)

**Comment by sonya** [comment]
This is the ruby snippet:

``` ruby
uri = URI('https://accounts.google.com/o/oauth2/revoke')
params = { :token => auth_client.access_token }
uri.query = URI.encode_www_form(params)
response = Net::HTTP.get(uri)
```

We currently don't save the `access_token` from the Omniauth callback. We only [grab the email address](https://github.com/codeforboston/cambridge_energy_app/blob/master/app/models/user.rb#L14) and throw away the rest of the response. So unless we make a bunch of changes the User model, we won't be able to initiate the revoke request because we don't have enough information.
