### ISSUE TITLE
Implement RSpec

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#30]
We have agreed that RSpec will be our testing tool of choice for the app. Testing helps catch errors in code so it is best to start building a good test suite for our codebase before it gets too large. Once RSpec is implemented we can then implement TravisCI for testing before deploys to production.

**Comment by mzagaja** [comment]
I added TravisCI and a badge, and also merged in the initial pull request to put in the testing gems. Now all we need are the actual tests to be written.

**Comment by mxie** [comment]
@mzagaja So is this just a matter of converting the existing Minitest specs over to RSpec now?

**Comment by mzagaja** [comment]
Yeah not too exciting but figured it'd be good housekeeping and a chance to familiarize with the codebase for someone. Sonya and I have only done RSpec testing so that was sort of the genesis of this task since we were planning to stick with RSpec going forward.

**Comment by itiswicked** [comment]
So I've implemented a bills controller spec, currently implementing teams controller spec.

**Comment by itiswicked** [comment]
Now working on invitations controller spec

**Comment by itiswicked** [comment]
I'm actually going to make this issue more granular, one issue to one missing test.

**Comment by itiswicked** [comment]
Cool, I'm closing this issue. Future missing tests should be should be added as their own separate issue.
