### ISSUE TITLE
Cannot accept or decline an invitation from another user

### ISSUE THREAD

**Issue by FrankCardillo** [codeforboston/cambridge_energy_app#306]
When a user has a pending invite and they click either accept or decline there is a routing error.

**Comment by shauncarland-old-account** [comment]
@FrankCardillo is this the PR associated w/this issue?
https://github.com/codeforboston/cambridge_energy_app/pull/305

**Comment by FrankCardillo** [comment]
@shauncarland No, that PR just fixes the issue of allowing people to send invitations. I discovered this particular issue while working on that. We can either add that into my existing PR or make another one. As it stands now though, that PR does not address this specific issue.
