### ISSUE TITLE
Explain scoring on the front end

### ISSUE THREAD

**Issue by jtrshelley** [codeforboston/cambridge_energy_app#309]
We need to explain how the score is calculated for the users

**Comment by tshelley** [comment]
Weather-normalizing:
xMonthHeatingAndCoolingDays = sumOverDaysMonth(abs(avgTemperature-65)). Source: http://www.energysmart.enernoc.com/how-to-calculate-weather-normalized-energy-consumption-using-heating-and-cooling-degree-days/

Personal Score Calculation
(lastMonth_kWh/lastMonthHeatingAndCoolingDays - thisMonth_kWh/thisMonthHeatingAndCoolingDays) / lastMonth_kWh/lastMonthHeatingAndCoolingDays ) * 100

**Comment by tshelley** [comment]
Future things to think about: if it turns out that people generally are only able to reduce their scores by 1-2%, we might want to consider mapping changes from 0-100 later.

**Comment by jtrshelley** [comment]
Verbiage: Your personal energy score is calculated by comparing your energy use this month with your energy use last month. Dramatic changes in weather are accounted for using heating and cooling days. [Source](https://github.com/codeforboston/cambridge_energy_app/issues/url).

See issue #312 for positioning of this text

**Comment by jtrshelley** [comment]
Your team energy score is calculated by summing the personal energy score of each member of your team.
