### ISSUE TITLE
Creating a Unit w/Guest Login

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#31]
Hello guys,

Wondering if @sonya or someone might be able to help me unscramble this nested attribute mess. I just pushed a new branch guest_login that is mostly there, it'll create a user if someone goes to create a new bill, but I can't get it to also accept and create the unit along with the user. Here is the console output when I try to test it:

```
Started POST "/bills" for 127.0.0.1 at 2015-12-19 16:30:21 -0500
Processing by BillsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"pRxJUxSF5//qZlwKaIp8qiCMp7zpVU5pFhq+0TT5F7ongTOamXbusx7cyRveaAQEF8hmSvFnvxxNThBTAkrkqA==", "bill"=>{"bill_received(1i)"=>"2015", "bill_received(2i)"=>"12", "bill_received(3i)"=>"19", "amount"=>"389", "units"=>{"number_occupants"=>"2"}}, "commit"=>"Create Bill"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
Unpermitted parameter: units
   (0.3ms)  BEGIN
  SQL (2.0ms)  INSERT INTO "bills" ("amount", "bill_received", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["amount", "389.0"], ["bill_received", "2015-12-19"], ["user_id", 1], ["created_at", "2015-12-19 21:30:21.353562"], ["updated_at", "2015-12-19 21:30:21.353562"]]
   (1.4ms)  COMMIT
Redirected to http://127.0.0.1:3000/bills/15
Completed 302 Found in 47ms (ActiveRecord: 5.6ms)


Started GET "/bills/15" for 127.0.0.1 at 2015-12-19 16:30:21 -0500
Processing by BillsController#show as HTML
  Parameters: {"id"=>"15"}
  Bill Load (0.3ms)  SELECT  "bills".* FROM "bills" WHERE "bills"."id" = $1 LIMIT 1  [["id", 15]]
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
  Rendered bills/show.html.erb within layouts/application (2.3ms)
Completed 200 OK in 175ms (Views: 173.5ms | ActiveRecord: 0.5ms)
```

I've been sort of following the advice at https://gorails.com/episodes/forum-nested-attributes-and-fields-for and referring to http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html.

Eventually I think we're going to have to create the unit when the user logins then perform some sort of check/merge once we obtain a full user street address. Any help/guidance on this is appreciated.

**Comment by sonya** [comment]
I have a commit https://github.com/codeforboston/cambridge_energy_app/commit/1875c7d6ae7c9e147d80a148fe864a4a84016809 which might be doing what you're saying? It just stupidly creates a Unit every time someone logs in. As you say we should do some kind of check/merge so we don't get a proliferation of redundant units.
