### ISSUE TITLE
E-Mail is Scrunched on Mobile Team Member View

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#329]
Just need to fix the table so it does not scrunch the user e-mail.

**Comment by FrankCardillo** [comment]
@mzagaja 
Hey I was wondering, it doesn't look like we ever actually collect the users' first and last names. Whether they sign up using devise or google I think we only ask for an email and a password. Should I just nix those from the listings of the team mates?

**Comment by mzagaja** [comment]
Yeah I think that makes sense.
