### ISSUE TITLE
Electric cars

### ISSUE THREAD

**Issue by Jilzost** [codeforboston/cambridge_energy_app#34]
Switching to an electric car is a good way to reduce one's carbon footprint. However it is common to charge the car at home, increasing energy costs. So the apparent impact of an electric car as viewed by the application (increased energy use) is the opposite of the real-world impact (reduced footprint.) 

Perhaps the application could account for "number of electric cars charged at home," or similar.

**Comment by mzagaja** [comment]
We talked with Seth about this issue and currently the competition does not account for electric car users. Therefore for the purpose of the Georgetown Energy Prize, unless Seth's feedback to them leads to some kind of affordance for this scenario, the use of electric cars is a negative.
