### ISSUE TITLE
Invite Someone to Join Your Team

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#37]
Invite a Team Member - probably need to use ActionMailer to do this and/or have some sort of notification appear on a team members dashboard.

Need to consider what we do if someone is already in the app versus it is not.

Need to develop e-mail copy they'll get if they've not used the app before.

For now we can put them through the regular on boarding process, but maybe they have a different faster on boarding flow than those who land from the website.

**Comment by mzagaja** [comment]
For design sprint:
1. What should the e-mail form look like in the context of the app itself?
2. What should the flow of the e-mail process be? Is it better to have them enter the recipient email on one page and then write the letter on the next page?
3. What should the e-mail that the invitee receives look like? Can a designer use a tool like Litmus to develop a responsive e-mail template to work with ActionMailer?

**Comment by mahtai** [comment]
Currently the setup I've built only works for people who are already on the app, since in particular it wants a user id to reference. Sending emails to people outside the app wouldn't be too difficult but I'm not entirely sure how to deal with them on the actual database side.

**Comment by mahtai** [comment]
For sending invitations to people: https://github.com/scambra/devise_invitable

**Comment by mahtai** [comment]
Current work, conditional on it working, only allows joining teams by invitation only. 
Still open is the new user process: if a new user joins the app without being invited by a team, they (should) get sent to the team index page. Still need mechanism for them to request to join a team, and also some way for them to distinguish between existing teams, which are currently listed by name only. What other data might a new user want when picking a team to join?
