### ISSUE TITLE
General Front End View Clean-up +DatePicker

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#39]
If someone wants to spend some time cleaning up the front end it'd be cool to have a better date picker like the one jQuery ui uses along with not stretching the forms completely to the border and adding appropriate titles to the app pages.

Good opportunity for any front-end people to get a little creative. We are using Foundation 5 (http://foundation.zurb.com).

**Comment by mzagaja** [comment]
So @Pilafonta is working on the DatePicker part here. However I think there is an opportunity for a designer to take a look at this template and suggest improvements to this template to make it more attractive.

**Comment by Pilafonta** [comment]
submitted a pull request.

**Comment by Pilafonta** [comment]
Merged pull request, added datepicker
