### ISSUE TITLE
OmniAuth oauth2-google missing credentials

### ISSUE THREAD

**Issue by Pilafonta** [codeforboston/cambridge_energy_app#63]
We need google API credentials in order to use the google-oauth2 gem, its currently throwing a 400 error when attempting to log in.

**Comment by mzagaja** [comment]
Can you push the branch you are working on this with so I can see your work so far, and also share where you encountered the error message or prompt related to this.

**Comment by Pilafonta** [comment]
fixed, can now login with gmail credentials
