### ISSUE TITLE
"Your Bill" Text Overlaps X-Axis Label If Your Bill is the First (Lowest) Bill

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#67]
I thought this would only go inside the bar the way I coded it but I guess not so this is a bug

**Comment by mzagaja** [comment]
If someone wants to use their javascript and CSS skills to tackle this front end issue please feel free to jump in otherwise this is on my back burner for now.

**Comment by ezrashim** [comment]
i'll look at them and see what i can do.

**Comment by VDuda** [comment]
Opened PR #98 to address this issue.

**Comment by mzagaja** [comment]
I think the red bar chart v. blue bars solution @mahtai went with works fine for now.
