### ISSUE TITLE
Bill Ordering is Not Working Right

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#68]
If you try entering a bill on the currently deployed production instance with 3 people in the apartment you'll see that not all the bills are in the order we expect them to be (lowest to highest).

**Comment by katilaw** [comment]
Matt is trying to reproduce the issue he was having. 

As far as I can tell the graph only compares bills for units with the same number of occupants. The data is being sorted and displayed properly as far as I can tell, no anomalies.

**Comment by itiswicked** [comment]
@mzagaja Are you still experiencing this issue?

After entering a bill as a guest, I am redirected to `graph/index`, and the graph properly shows the bills lowest to highest.

**Comment by mzagaja** [comment]
I think this might have been due to a local database issue so I'm going to close this.
