### ISSUE TITLE
Bill Validations Breaks Initial Guest Data Entry

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#71]
<img width="1060" alt="screenshot 2016-03-13 16 05 31" src="https://cloud.githubusercontent.com/assets/565647/13730986/74303b24-e935-11e5-8d79-6d96878e797c.png">

This issue was introduced by #66. I restored the branch and issued a PR to revert #66 so that master continues to work until this is fixed.

**Comment by jrpespisa** [comment]
I'm going to work on fixing this. 
The issue is syntax in the model validations. Should be an easy fix.

**Comment by Pilafonta** [comment]
Is this still an issue?

**Comment by JerJohn15** [comment]
@Pilafonta 

It doesn't seem like it is, as I've tried testing this on my end (both on the live site and the local browser) and could not reproduce the error message as shown in the image. I think this issue should be closed.

**Comment by itiswicked** [comment]
Can confirm, no issues in the current master
