### ISSUE TITLE
Front end styling/design mocks

### ISSUE THREAD

**Issue by cmajel** [codeforboston/cambridge_energy_app#77]
@mzagaja creating a separate issue to complete site design. I have one main styling concept I like and wanted to share where I am. Indiv style tiles w colors + fonts are included as well as quick mocks for form + dashboard pages to test out the design direction. The main difference between these are shading + font stacks - feeling pretty good about the coloring. I personally am leaning towards D.

Feedback much appreciated and should be enough to get some basic styling on the site. 

![layout-compare](https://cloud.githubusercontent.com/assets/2374206/13917160/7a5148e4-ef35-11e5-8859-b92933779512.png)
[style-tiles.zip](https://github.com/codeforboston/cambridge_energy_app/files/182088/style-tiles.zip)

**Comment by cmajel** [comment]
survey here: https://www.surveymonkey.com/r/P9SD87W

**Comment by kvotolato3** [comment]
Which one was the winner? D?
