### ISSUE TITLE
Investigate user testing options

### ISSUE THREAD

**Issue by cmajel** [codeforboston/cambridge_energy_app#79]
Based on our convo today, a few notes. 

We should do some user testing once we have a good idea of the site structure and the initial styles. The fastest/easiest way to do this is with a clickable invision prototype (no code required, just mocks) and some city employees. We'd also want to decide ahead of time what we want to test (how easy it is to get around the site? is onboarding smooth? do people understand/get teams as a concept?)

https://www.invisionapp.com

**Comment by mzagaja** [comment]
I put in a request to setup an appointment with the Pivotal Labs office hours to script a user test.
