### ISSUE TITLE
Profile Complete Meter

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#8]
One feature we want is a "profile complete meter" that will let a user know how complete their profile is. We should figure out what a constitutes a complete profile and then what pieces of information are worth what percentage of whatever meter representation we create.

**Comment by mahtai** [comment]
Address
Email (phone?)
Energy types (electricity, gas, what kind of heating)
Building type? (House, apartment)
Number of people in household?

**Comment by mahtai** [comment]
Created profile_complete_meter function, returns integer percentage. Should I try to make a little graphic meter?

**Comment by mzagaja** [comment]
Maybe one of our design surge friends can design a great looking meter for us to use with your code!

**Comment by mahtai** [comment]
Profile complete meter is acting up, not quite recognizing when something is blank.

**Comment by mzagaja** [comment]
We can use the progress element: https://css-tricks.com/html5-progress-element/ but may have to refactor to get it working.
