### ISSUE TITLE
Navbar and Styling Branches Failed to Merge Properly

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#89]
https://github.com/codeforboston/cambridge_energy_app/pull/84 and https://github.com/codeforboston/cambridge_energy_app/pull/69 did not play well together, I think because foundation was removed in styling. I think the stylesheet just needs to be updated for the navbar to work again if someone wants to tackle this.

**Comment by ezrashim** [comment]
I can look into this, but might need to work with @cmajel to preserve her changes.

**Comment by cmajel** [comment]
@ezrashim I couldn't be there tonight but I'm around this week if you want me to take a look. If you are liking working with foundation I can also see if I can preserve both.

**Comment by QuinnLee** [comment]
I took a look and noticed that `navbar.scss` should be in `components/navbar.scss` in the styles dir.

**Comment by mzagaja** [comment]
This suggestion made some progress but still is not quite there with the move, the background turns black but it does not become a functional  so more work is needed to fix this merge.
