### ISSUE TITLE
ActionMailer E-Mail Bugs and Fixes

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#90]
This is a sample e-mail I got when testing the new e-mail features:

<img width="610" alt="screenshot 2016-04-10 23 43 07" src="https://cloud.githubusercontent.com/assets/565647/14416281/145d9fa0-ff76-11e5-8d33-8d7ecfebc1a8.png">

It needs the following fixes
- [x] UI in invitation flow to make sure invitee has a name, or change text to not use name
- [x] Get variables working in the subject line
- [x] Fix sent from for password e-mails to be from a real e-mail

**Comment by mahtai** [comment]
Make sure that the sendgrid stuff is working on the live site, because local sites don't include the username and password and so give "550: Unauthenticated..." errors.
Bug 2 on Jeremiah's report
