### ISSUE TITLE
Unit and Integration Tests for features from sendgridfix branch

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#91]
We should add an integration tests for creating a team and inviting teammates and joining a team along with appropriate unit tests for the models. See https://github.com/codeforboston/cambridge_energy_app/pull/72 for the scope of this.

**Comment by itiswicked** [comment]
@mzagaja I think we need unit tests for everything at this point. Also, I know there are a few controller tests missing. Should I open an issue for each test to make things more granular?
