### ISSUE TITLE
Domains discussion

### ISSUE THREAD

**Issue by kvotolato3** [codeforboston/cambridge_energy_app#95]
Since we're going to need a domain from which to send emails, let's open up the discussion here. If anyone has ideas, please leave a comment! I will start by saying I'm more in favor of the ".org" and ".net"  options since they are non-commercial in nature, but I also wouldn't be opposed to a ".com". Below are some ideas, which I looked up on Hover, and their yearly fees. What does the rest of our team think? 
### Ideas for EnerSave domains
1. enersavecambridge.com - $12.99
2. enersavecambridge.org - $12.99
3. enersavecambridge.net - $13.60
4. enersaveapp.com - $12.99
5. enersaveapp.net - $13.60
6. enersaveapp.org - $12.99

**Comment by mzagaja** [comment]
Right now I like the app ones because they are shorter. I agree that .org is probably the more sensible one, unless there is a fun domain name end we want to try. Enersa.ve?

**Comment by mzagaja** [comment]
Closing this since we went with enersaveapp.org. Thanks for investigating and leading this Kathleen!
